version: '3'

vars:
  TOOL_DIR: "{{.USER_WORKING_DIR}}/bin"
  IMAGE_NAME: "ghcr.io/datum-cloud/search"
  IMAGE_TAG: "dev"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list
    silent: true

  # Build tasks
  build:
    desc: Build the search binary
    cmds:
      - |
        set -e
        echo "Building search..."
        mkdir -p {{.TOOL_DIR}}

        # Get git information for version injection
        GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
        VERSION="v0.0.0-dev+${GIT_COMMIT:0:7}"
        GIT_TREE_STATE="clean"
        if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
          GIT_TREE_STATE="dirty"
        fi
        BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo "unknown")

        echo "Version: ${VERSION}, Commit: ${GIT_COMMIT:0:7}, Tree: ${GIT_TREE_STATE}"

        go build \
          -ldflags="-X 'go.datum.net/search/internal/version.Version=${VERSION}' \
                    -X 'go.datum.net/search/internal/version.GitCommit=${GIT_COMMIT}' \
                    -X 'go.datum.net/search/internal/version.GitTreeState=${GIT_TREE_STATE}' \
                    -X 'go.datum.net/search/internal/version.BuildDate=${BUILD_DATE}'" \
          -o {{.TOOL_DIR}}/search ./cmd/search
        echo "✅ Binary built: {{.TOOL_DIR}}/search"
    silent: true

  # Development tasks
  dev:build:
    desc: Build the Search server container image for development
    silent: true
    cmds:
      - |
        set -e
        echo "Building Search server container image: {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

        # Get git information for version injection
        GIT_COMMIT=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
        VERSION="v0.0.0-dev+${GIT_COMMIT:0:7}"
        GIT_TREE_STATE="clean"
        if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
          GIT_TREE_STATE="dirty"
        fi
        BUILD_DATE=$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo "unknown")

        docker build \
          --build-arg VERSION="${VERSION}" \
          --build-arg GIT_COMMIT="${GIT_COMMIT}" \
          --build-arg GIT_TREE_STATE="${GIT_TREE_STATE}" \
          --build-arg BUILD_DATE="${BUILD_DATE}" \
          -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          .

        echo "✅ Container image built: {{.IMAGE_NAME}}:{{.IMAGE_TAG}}"

  # Code generation tasks
  generate:
    desc: Generate deepcopy and client code
    cmds:
      - |
        set -e
        echo "Generating code..."

        # Run code generators
        go run k8s.io/code-generator/cmd/deepcopy-gen \
          --go-header-file hack/boilerplate.go.txt \
          --output-file zz_generated.deepcopy.go \
          --bounding-dirs go.datum.net/search/pkg/apis \
          go.datum.net/search/pkg/apis/search/v1alpha1

        echo "✅ Code generation complete"
    silent: true

  # Test tasks
  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...

  # Cleanup tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.TOOL_DIR}}
      - rm -rf .task
      - echo "✅ Cleaned build artifacts"
    silent: true

  # Format and lint
  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...
      - echo "✅ Code formatted"
    silent: true

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...
      - echo "✅ Vet complete"
    silent: true
